language: cpp

compiler:
  - g++

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y cmake
  - sudo apt-get install -y libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd $TRAVIS_BUILD_DIR

script:
  - g++ -isystem /usr/include -pthread -o test_main tests/test_main.cpp /usr/lib/libgtest.a /usr/lib/libgtest_main.a
  - ./test_main
